call pathogen#infect()
call pathogen#helptags()

" Helper functions begin, will only work if you have ConqueTerm installed
function RunOrRaiseBash()
	if bufexists('/bin/bash - 1')
		buffer bash
	else
		ConqueTerm /bin/bash
	endif
endfunction

filetype plugin on

" Settings
"se tabstop=2
"se shiftwidth=2
se enc=utf-8
se fenc=utf-8
se termencoding=utf-8
" Ignore case while searching
se ignorecase
" Match [] with %, too
se matchpairs=(:),{:},[:]
" Store swap files in this directory
se directory=~/.vim/tmp
se smartcase
" Searches do not wrap
se nowrapscan
se nosmartindent
" Use cindent (powerful!)
se cindent
" This is just for gvim. a autoyanks everything in the 'v' mode
se guioptions=a
se wildmenu
se wildmode=longest,list
se sh=/bin/bash
se scrolloff=3
se listchars=tab:>-,trail:·,eol:$
se hidden
" I removed 'r' because that adds an asterisk at the beginning of doxygen
" comments
se formatoptions=ql
" Somewhat sge style indentation
se cino=c0,C0,g0,N-s,(s,p0,t0,)100,h0,u0

" The mapleader key is used by some plugins as a shortcut in they keyboard
" mappings. The standard is \
let mapleader = ','

" Highlight trailing whitespace and leading (non-tab) whitespace
autocmd ColorScheme c,cpp,objcpp,objcpp,sh highlight ExtraWhitespace ctermbg=red guibg=red
autocmd BufEnter c,cpp,objcpp,objcpp,sh match ExtraWhitespace /\s\+$/ | 2match ExtraWhitespace /^ \+/

" Color scheme
colo desert

" Mappings
map <C-x><C-f> :FufCoverageFile<CR>
" F keys
map <F1> :ErrorAtCursor<CR>
map <F2> :make!<CR>
map <F3> :FSHere<CR>
map <F4> :call RunOrRaiseBash()<CR>
map <F5> :r !/home/philipp/.vim/suggest %<CR>
map <F7> :0r! /home/philipp/projects/sgeutils/build/bin/generate_includeguard %:p<CR>:1<CR>
"map <F9> :OpenIncludePath<CR>
"map <F10> :InsertIncludeDirective<CR>
map <up> :cp<CR>
map <down> :cn<CR>
map <C-h> 5h
map <C-j> 5j
map <C-k> 5k
map <C-l> 5l
map <C-i> :AddIncludeLine<CR>
" Disable the pesky command line window
map q: <nop>
nnoremap <Leader>e :e <C-r>=expand('%:p:h')<CR>
nnoremap <Leader>s :sp <C-r>=expand('%:p:h')<CR>
nnoremap <Leader>v :vsp <C-r>=expand('%:p:h')<CR>
nnoremap <Leader>r :r <C-r>=expand('%:p:h')<CR>

" Syntax files
au BufNewFile,BufRead *.tex,*.latex se tw=80
au BufNewFile,BufRead *.cl set ft=opencl
au BufEnter *.cl setl makeprg=/home/philipp/projects/spacegameengine/build/bin/sgeopencl_syntax_checkerexample\ %:p

"runtime macros/matchit.vim

se makeprg=cd\ build;make\ -j3

au! BufEnter *.cpp let b:fswitchdst = 'hpp,h' | let b:fswitchlocs = 'reg:/src/include/'
au! BufEnter *.hpp let b:fswitchdst = 'cpp,c' | let b:fswitchlocs = 'reg:/include/src/'
au VimResized * wincmd =

" Assume we have enough space to show more of the completion line
let g:fuf_maxMenuWidth = 200
" Usually when you enter 'foobar', this will not match 'foo/bar'. With this,
" it will
let g:fuf_splitPathMatching = 1
let g:fuf_fuzzyRefining = 1

" glsl stuff
command SetGLSLFileType call SetGLSLFileType()
function SetGLSLFileType()
	for item in getline(1,10)
		if item =~ "#version 400"
			execute ':set filetype=glsl400'
			return
		endif
		if item =~ "#version 330"
			execute ':set filetype=glsl330'
			return
		endif
	endfor

	execute ':set filetype=glsl'
endfunction

au BufNewFile,BufRead *.frag,*.vert,*.fp,*.vp,*.glsl SetGLSLFileType
au! BufRead,BufNewFile *.json se ft=json
au! BufRead,BufNewFile *.doxygen se ft=doxygen

" This is supposed to be faster, but it crashes
"let g:clang_use_library = 1
"let g:clang_library_path = '/usr/lib64/llvm'
let g:inccomplete_showdirs = 1
let g:inccomplete_addclosebracket = 'never'
let g:inccomplete_findcmd = '/usr/bin/find'
"set completeopt=longest,menuone
set completeopt=longest
