#!/bin/bash

set -u

source "@SGEBUILD_COMMON_DIR@/sgebuild-common"


# Setup main config

SGEBUILD_ALL_CONFIG="${SGEBUILD_CONFIG_DIR}/all_config.sh"

# Display help message

if [[ $# == 1 && "$1" == "--help" ]] ; then

echo "
Usage: $0 [parameters]

This command builds all sgebuild configs in one go. It relies on sgebuild,
therefore see sgebuild --help, too.

Parameters:
  - parameters: Additional parameters that are passed to the sgebuild
    invocations

Two additional config files are read to determine which targets to build in the
following order:
  - The sgebuild all config file: ${SGEBUILD_ALL_CONFIG}
  - The project all config file: \${SGEBUILD_PROJECT_CONFIG_DIR}/all_config.sh

The following variables are read from the config files:

sgebuild all config (mandatory):
  SGEBUILD_ALL_TARGETS:
    An array of targets to build for all projects, for example:

    SGEBUILD_ALL_TARGETS=(
      \"clang\"
      \"gcc\"
    )

project all config (optional):
  SGEBUILD_ALL_PROJECT_TARGETS:
    An array of targets to additionally build for this project, for example:

    SGEBUILD_ALL_PROJECT_TARGETS=(
      \"gcc_flto\"
    )
  SGEBUILD_ALL_PROJECT_IGNORE_TARGETS:
    An array of targets to ignore for this project, for example:

    SGEBUILD_ALL_PROJECT_IGNORE_TARGETS=(
      \"mingw\"
    )
"

exit

fi

# Read the main config

check_file "${SGEBUILD_ALL_CONFIG}"

source "${SGEBUILD_ALL_CONFIG}"

check_variable "SGEBUILD_ALL_TARGETS" "${SGEBUILD_ALL_CONFIG}"


# Read the project config

SGEBUILD_PROJECT_ALL_CONFIG="${SGEBUILD_PROJECT_CONFIG_DIR}/all_config.sh"

[[ -e "${SGEBUILD_PROJECT_ALL_CONFIG}" ]] && source "${SGEBUILD_PROJECT_ALL_CONFIG}"

SGEBUILD_ALL_TARGETS=(
	"${SGEBUILD_ALL_TARGETS[@]}"
	"${SGEBUILD_ALL_PROJECT_TARGETS[@]}"
)

for target in "${SGEBUILD_ALL_TARGETS[@]}" ; do
	ignore=false
	for ignore_target in "${SGEBUILD_ALL_PROJECT_IGNORE_TARGETS[@]}" ; do
		if [[ "${target}" = "${ignore_target}" ]] ; then
			ignore=true
			echo "Ignoring target ${target}"
		fi
	done

	if ! ${ignore} ; then
		"@SGEBUILD_BIN_DIR@/sgebuild" "${target}" "$@" || die "Aborted"
	fi
done
