#!/usr/bin/env bash

LIBS=(--library sge --library fcppt)
DIRS=(
	check_includes
	compile_headers
	file_switch
	generate_includeguard
	prettify_includes
	update_cmake
	update_license
)

prettify_includes "${LIBS[@]}" "${DIRS[@]}"
